module:
  mounts:
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
params:
  authors:
    thumbnail:
      desktop: "100x100"
      mobile: "100x100"
    image:
      desktop: "100x100"
      mobile: "100x100"
    post:
      desktop: "50x50"
      mobile: "50x50"

# Default
permalinks:
  authors: /news/:slug/
taxonomies:
  author: authors